### ISSUE TITLE
include what you use source lax on transitive headers through corresponding header

### ISSUE THREAD

**Issue by geoffviola** [cpplint/cpplint#218]
When cpplint is run on a source file, it counts the includes in its corresponding header file as included.

https://github.com/cpplint/cpplint/blob/fa12a0bbdafa15291276ddd2a2dcd2ac7a2ce4cb/cpplint.py#L6127-L6128

But the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Include_What_You_Use) states that

> Do not rely on transitive inclusions. This allows people to remove no-longer-needed #include statements from their headers without breaking clients. This also applies to related headers - foo.cc should include bar.h if it uses a symbol from it even if foo.h includes bar.h.

Should cpplint follow that?

**Comment by tkruse** [comment]
I agree that the two contradict each other. Might be good to ask upstream in https://github.com/google/styleguide

**Comment by aaronliu0130** [comment]
Fixed in e3482c5

**Comment by andioz** [comment]
I have a question regarding this: it would be nice to have a possibility to disable this new rule by a command line filter, because it breaks existing code now. Using `--filter -build/include_what_you_use` is not an option, it would disable all checks, even for header files too, right? 

Right now I'm in trouble, shall I stick with an older version of `cpplint` or can I upgrade without getting a ton of warnings which cannot be solved in the near future for our project?

**Comment by andioz** [comment]
I have a question regarding this: it would be nice to have a possibility to disable this new rule by a command line filter, because it breaks existing code now. Using `--filter -build/include_what_you_use` is not an option, it would disable all checks, even for header files too, right? 

Right now I'm in trouble, shall i stick with an older version of `cpplint` or can I upgrade without getting a ton of warnings which cannot be solved in the near future for our project?

**Comment by aaronliu0130** [comment]
In my opinion, the best option is to add the includes for the reasons outlined in the style guide; it does no harm and only good.

The code for this was removed entirely in e3482c53590e9ff61280a0cb5cd61fc692570fa6; if you really want to check transitive includes, you could revert that commit within the source code and then `pip install .` or remain on an old version.

**Comment by andioz** [comment]
Thanks for the quick response. Well, updating 1k+ source files in our restricted project is no option, at least at the moment, unfortunately. I see, I have to a) disable IWYU at all, b) get used to ignore this warnings on my own, or c) pin to an old version.
